// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>synesis</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace synesis {
	using System;
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System.Collections;
	using System.Xml.Schema;
	using System.ComponentModel;


	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = false)]
	public partial class AntishakerCrop : System.ComponentModel.INotifyPropertyChanged {

        private float xOffsField;

        private float yOffsField;

        private float cropWidthField;

        private float cropHeightField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public float XOffs {
			get {
				return this.xOffsField;
			}
			set {
				if ((xOffsField.Equals(value) != true)) {
					this.xOffsField = value;
					this.OnPropertyChanged("XOffs");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public float YOffs {
			get {
				return this.yOffsField;
			}
			set {
				if ((yOffsField.Equals(value) != true)) {
					this.yOffsField = value;
					this.OnPropertyChanged("YOffs");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public float CropWidth {
			get {
				return this.cropWidthField;
			}
			set {
				if ((cropWidthField.Equals(value) != true)) {
					this.cropWidthField = value;
					this.OnPropertyChanged("CropWidth");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public float CropHeight {
			get {
				return this.cropHeightField;
			}
			set {
				if ((cropHeightField.Equals(value) != true)) {
					this.cropHeightField = value;
					this.OnPropertyChanged("CropHeight");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = false)]
	public partial class MarkerCalibration : System.ComponentModel.INotifyPropertyChanged {

		private object itemField;

		[System.Xml.Serialization.XmlElementAttribute("CombinedMarkerCalibration", typeof(CombinedMarkerCalibration), Order = 0)]
		[System.Xml.Serialization.XmlElementAttribute("HeightMarkerCalibration", typeof(HeightMarkerCalibration), Order = 0)]
		public object Item {
			get {
				return this.itemField;
			}
			set {
				if ((this.itemField != null)) {
					if ((itemField.Equals(value) != true)) {
						this.itemField = value;
						this.OnPropertyChanged("Item");
					}
				} else {
					this.itemField = value;
					this.OnPropertyChanged("Item");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = true)]
	public partial class CombinedMarkerCalibration : System.ComponentModel.INotifyPropertyChanged {

		private CombinedMarker[] combinedMarkersField;

		[System.Xml.Serialization.XmlElementAttribute("CombinedMarkers", Order = 0)]
		public CombinedMarker[] CombinedMarkers {
			get {
				return this.combinedMarkersField;
			}
			set {
				if ((this.combinedMarkersField != null)) {
					if ((combinedMarkersField.Equals(value) != true)) {
						this.combinedMarkersField = value;
						this.OnPropertyChanged("CombinedMarkers");
					}
				} else {
					this.combinedMarkersField = value;
					this.OnPropertyChanged("CombinedMarkers");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = true)]
	public partial class CombinedMarker : System.ComponentModel.INotifyPropertyChanged {

		private int heightField;

		private int widthField;

		private Rect[] rectanglesField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public int Height {
			get {
				return this.heightField;
			}
			set {
				if ((heightField.Equals(value) != true)) {
					this.heightField = value;
					this.OnPropertyChanged("Height");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public int Width {
			get {
				return this.widthField;
			}
			set {
				if ((widthField.Equals(value) != true)) {
					this.widthField = value;
					this.OnPropertyChanged("Width");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Rectangles", Order = 2)]
		public Rect[] Rectangles {
			get {
				return this.rectanglesField;
			}
			set {
				if ((this.rectanglesField != null)) {
					if ((rectanglesField.Equals(value) != true)) {
						this.rectanglesField = value;
						this.OnPropertyChanged("Rectangles");
					}
				} else {
					this.rectanglesField = value;
					this.OnPropertyChanged("Rectangles");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = true)]
	public partial class Rect : System.ComponentModel.INotifyPropertyChanged {

		private Point leftTopField;

		private Point rightBottomField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public Point LeftTop {
			get {
				return this.leftTopField;
			}
			set {
				if ((this.leftTopField != null)) {
					if ((leftTopField.Equals(value) != true)) {
						this.leftTopField = value;
						this.OnPropertyChanged("LeftTop");
					}
				} else {
					this.leftTopField = value;
					this.OnPropertyChanged("LeftTop");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public Point RightBottom {
			get {
				return this.rightBottomField;
			}
			set {
				if ((this.rightBottomField != null)) {
					if ((rightBottomField.Equals(value) != true)) {
						this.rightBottomField = value;
						this.OnPropertyChanged("RightBottom");
					}
				} else {
					this.rightBottomField = value;
					this.OnPropertyChanged("RightBottom");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = true)]
	public partial class Point : System.ComponentModel.INotifyPropertyChanged {

        private float xField;

        private float yField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public float X {
			get {
				return this.xField;
			}
			set {
				if ((xField.Equals(value) != true)) {
					this.xField = value;
					this.OnPropertyChanged("X");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public float Y {
			get {
				return this.yField;
			}
			set {
				if ((yField.Equals(value) != true)) {
					this.yField = value;
					this.OnPropertyChanged("Y");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = true)]
	public partial class HeightMarkerCalibration : System.ComponentModel.INotifyPropertyChanged {

		private float focalLengthField;

		private MatrixFormat matrixFormatField;

		private HeightMarker[] heightMarkersField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public float FocalLength {
			get {
				return this.focalLengthField;
			}
			set {
				if ((focalLengthField.Equals(value) != true)) {
					this.focalLengthField = value;
					this.OnPropertyChanged("FocalLength");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public MatrixFormat MatrixFormat {
			get {
				return this.matrixFormatField;
			}
			set {
				if ((matrixFormatField.Equals(value) != true)) {
					this.matrixFormatField = value;
					this.OnPropertyChanged("MatrixFormat");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("HeightMarkers", Order = 2)]
		public HeightMarker[] HeightMarkers {
			get {
				return this.heightMarkersField;
			}
			set {
				if ((this.heightMarkersField != null)) {
					if ((heightMarkersField.Equals(value) != true)) {
						this.heightMarkersField = value;
						this.OnPropertyChanged("HeightMarkers");
					}
				} else {
					this.heightMarkersField = value;
					this.OnPropertyChanged("HeightMarkers");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	public enum MatrixFormat {

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1")]
		Item1,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("2/3")]
		Item23,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1/1,6")]
		Item116,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1/1,8")]
		Item118,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1/2")]
		Item12,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1/2,3")]
		Item123,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1/2,5")]
		Item125,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1/2,7")]
		Item127,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1/3")]
		Item13,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1/3,2")]
		Item132,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1/3,6")]
		Item136,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1/4")]
		Item14,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1/5")]
		Item15,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1/6")]
		Item16,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1/8")]
		Item18,
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = true)]
	public partial class HeightMarker : System.ComponentModel.INotifyPropertyChanged {

		private int heightField;

		private SurfaceNormal[] surfaceNormalsField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public int Height {
			get {
				return this.heightField;
			}
			set {
				if ((heightField.Equals(value) != true)) {
					this.heightField = value;
					this.OnPropertyChanged("Height");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("SurfaceNormals", Order = 1)]
		public SurfaceNormal[] SurfaceNormals {
			get {
				return this.surfaceNormalsField;
			}
			set {
				if ((this.surfaceNormalsField != null)) {
					if ((surfaceNormalsField.Equals(value) != true)) {
						this.surfaceNormalsField = value;
						this.OnPropertyChanged("SurfaceNormals");
					}
				} else {
					this.surfaceNormalsField = value;
					this.OnPropertyChanged("SurfaceNormals");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = true)]
	public partial class SurfaceNormal : System.ComponentModel.INotifyPropertyChanged {

		private Point pointField;

        private float heightField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public Point Point {
			get {
				return this.pointField;
			}
			set {
				if ((this.pointField != null)) {
					if ((pointField.Equals(value) != true)) {
						this.pointField = value;
						this.OnPropertyChanged("Point");
					}
				} else {
					this.pointField = value;
					this.OnPropertyChanged("Point");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public float Height {
			get {
				return this.heightField;
			}
			set {
				if ((heightField.Equals(value) != true)) {
					this.heightField = value;
					this.OnPropertyChanged("Height");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = false)]
	public partial class UserRegion : System.ComponentModel.INotifyPropertyChanged {

		private Rose roseField;

		private Point[] pointsField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public Rose Rose {
			get {
				return this.roseField;
			}
			set {
				if ((this.roseField != null)) {
					if ((roseField.Equals(value) != true)) {
						this.roseField = value;
						this.OnPropertyChanged("Rose");
					}
				} else {
					this.roseField = value;
					this.OnPropertyChanged("Rose");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Points", Order = 1)]
		public Point[] Points {
			get {
				return this.pointsField;
			}
			set {
				if ((this.pointsField != null)) {
					if ((pointsField.Equals(value) != true)) {
						this.pointsField = value;
						this.OnPropertyChanged("Points");
					}
				} else {
					this.pointsField = value;
					this.OnPropertyChanged("Points");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = true)]
	public partial class Rose : System.ComponentModel.INotifyPropertyChanged {

		private bool upField;

		private bool upRightField;

		private bool rightField;

		private bool downRightField;

		private bool downField;

		private bool downLeftField;

		private bool leftField;

		private bool upLeftField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public bool Up {
			get {
				return this.upField;
			}
			set {
				if ((upField.Equals(value) != true)) {
					this.upField = value;
					this.OnPropertyChanged("Up");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public bool UpRight {
			get {
				return this.upRightField;
			}
			set {
				if ((upRightField.Equals(value) != true)) {
					this.upRightField = value;
					this.OnPropertyChanged("UpRight");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public bool Right {
			get {
				return this.rightField;
			}
			set {
				if ((rightField.Equals(value) != true)) {
					this.rightField = value;
					this.OnPropertyChanged("Right");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public bool DownRight {
			get {
				return this.downRightField;
			}
			set {
				if ((downRightField.Equals(value) != true)) {
					this.downRightField = value;
					this.OnPropertyChanged("DownRight");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public bool Down {
			get {
				return this.downField;
			}
			set {
				if ((downField.Equals(value) != true)) {
					this.downField = value;
					this.OnPropertyChanged("Down");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public bool DownLeft {
			get {
				return this.downLeftField;
			}
			set {
				if ((downLeftField.Equals(value) != true)) {
					this.downLeftField = value;
					this.OnPropertyChanged("DownLeft");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public bool Left {
			get {
				return this.leftField;
			}
			set {
				if ((leftField.Equals(value) != true)) {
					this.leftField = value;
					this.OnPropertyChanged("Left");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 7)]
		public bool UpLeft {
			get {
				return this.upLeftField;
			}
			set {
				if ((upLeftField.Equals(value) != true)) {
					this.upLeftField = value;
					this.OnPropertyChanged("UpLeft");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = false)]
	public partial class RegionPoints : System.ComponentModel.INotifyPropertyChanged {

		private Point[] pointsField;

		[System.Xml.Serialization.XmlElementAttribute("Points", Order = 0)]
		public Point[] Points {
			get {
				return this.pointsField;
			}
			set {
				if ((this.pointsField != null)) {
					if ((pointsField.Equals(value) != true)) {
						this.pointsField = value;
						this.OnPropertyChanged("Points");
					}
				} else {
					this.pointsField = value;
					this.OnPropertyChanged("Points");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = false)]
	public partial class TripWirePoints : System.ComponentModel.INotifyPropertyChanged {

		private Point p1Field;

		private Point p2Field;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public Point P1 {
			get {
				return this.p1Field;
			}
			set {
				if ((this.p1Field != null)) {
					if ((p1Field.Equals(value) != true)) {
						this.p1Field = value;
						this.OnPropertyChanged("P1");
					}
				} else {
					this.p1Field = value;
					this.OnPropertyChanged("P1");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public Point P2 {
			get {
				return this.p2Field;
			}
			set {
				if ((this.p2Field != null)) {
					if ((p2Field.Equals(value) != true)) {
						this.p2Field = value;
						this.OnPropertyChanged("P2");
					}
				} else {
					this.p2Field = value;
					this.OnPropertyChanged("P2");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = false)]
	public partial class DirectionAlarm : System.ComponentModel.INotifyPropertyChanged {

		private bool enabledField;

		private Rose roseField;

		private float minShiftField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public bool Enabled {
			get {
				return this.enabledField;
			}
			set {
				if ((enabledField.Equals(value) != true)) {
					this.enabledField = value;
					this.OnPropertyChanged("Enabled");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public Rose Rose {
			get {
				return this.roseField;
			}
			set {
				if ((this.roseField != null)) {
					if ((roseField.Equals(value) != true)) {
						this.roseField = value;
						this.OnPropertyChanged("Rose");
					}
				} else {
					this.roseField = value;
					this.OnPropertyChanged("Rose");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public float MinShift {
			get {
				return this.minShiftField;
			}
			set {
				if ((minShiftField.Equals(value) != true)) {
					this.minShiftField = value;
					this.OnPropertyChanged("MinShift");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = false)]
	public partial class SpeedAlarm : System.ComponentModel.INotifyPropertyChanged {

		private bool enabledField;

		private float speedField;

		private int timeField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public bool Enabled {
			get {
				return this.enabledField;
			}
			set {
				if ((enabledField.Equals(value) != true)) {
					this.enabledField = value;
					this.OnPropertyChanged("Enabled");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public float Speed {
			get {
				return this.speedField;
			}
			set {
				if ((speedField.Equals(value) != true)) {
					this.speedField = value;
					this.OnPropertyChanged("Speed");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public int Time {
			get {
				return this.timeField;
			}
			set {
				if ((timeField.Equals(value) != true)) {
					this.timeField = value;
					this.OnPropertyChanged("Time");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = false)]
	public partial class LoiteringAlarm : System.ComponentModel.INotifyPropertyChanged {

		private bool enabledField;

		private float radiusField;

		private int timeField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public bool Enabled {
			get {
				return this.enabledField;
			}
			set {
				if ((enabledField.Equals(value) != true)) {
					this.enabledField = value;
					this.OnPropertyChanged("Enabled");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public float Radius {
			get {
				return this.radiusField;
			}
			set {
				if ((radiusField.Equals(value) != true)) {
					this.radiusField = value;
					this.OnPropertyChanged("Radius");
				}
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public int Time {
			get {
				return this.timeField;
			}
			set {
				if ((timeField.Equals(value) != true)) {
					this.timeField = value;
					this.OnPropertyChanged("Time");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = false)]
	public partial class AbandonedItemAlarm : System.ComponentModel.INotifyPropertyChanged {

		private bool enabledField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public bool Enabled {
			get {
				return this.enabledField;
			}
			set {
				if ((enabledField.Equals(value) != true)) {
					this.enabledField = value;
					this.OnPropertyChanged("Enabled");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.synesis.ru/onvif/VideoAnalytics")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.synesis.ru/onvif/VideoAnalytics", IsNullable = false)]
	public partial class RegionMotionAlarm : System.ComponentModel.INotifyPropertyChanged {

		private bool enabledField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public bool Enabled {
			get {
				return this.enabledField;
			}
			set {
				if ((enabledField.Equals(value) != true)) {
					this.enabledField = value;
					this.OnPropertyChanged("Enabled");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public virtual void OnPropertyChanged(string propertyName) {
			System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
			if ((handler != null)) {
				handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
